### ISSUE TITLE
Function addDebitReseller

### ISSUE THREAD

**Issue by juniorriau** [liquidregistrar/liquid-php#1]
Hallo

saya memakai liqu php api, tetapi untuk fungsi debit note ke subreseller tidak ada, saya coba buat seperti ini
`public function addDebitReseller($reseller_id, $amount, $description, $substrac=1)
    {
 
        // verify the required parameter 'customer_id' is set
        if ($reseller_id === null) {
            throw new \InvalidArgumentException('Missing the required parameter $customer_id when calling addDebitReseller');
        }
        // verify the required parameter 'amount' is set
        if ($amount === null) {
            throw new \InvalidArgumentException('Missing the required parameter $amount when calling addDebitReseller');
        }
        // verify the required parameter 'description' is set
        if ($description === null) {
            throw new \InvalidArgumentException('Missing the required parameter $description when calling addDebitReseller');
        }
        if ($substrac === null) {
            throw new \InvalidArgumentException('Missing the required parameter $substract when calling addDebitReseller');
        }
 
        // parse inputs
        $resourcePath = "/manage/resellers/{reseller_id}/add_reseller_debit_note";
        $resourcePath = str_replace("{format}", "json", $resourcePath);
        $method = "POST";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = ApiClient::selectHeaderAccept(array());
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = ApiClient::selectHeaderContentType(array());
 
 
 
        // path params
        if ($reseller_id !== null) {
            $resourcePath = str_replace(
                "{" . "reseller_id" . "}",
                $this->apiClient->getSerializer()->toPathValue($reseller_id),
                $resourcePath
            );
        }
        // form params
        if ($amount !== null) {
            $formParams['amount'] = $this->apiClient->getSerializer()->toFormValue($amount);
        }// form params
        if ($description !== null) {
            $formParams['description'] = $this->apiClient->getSerializer()->toFormValue($description);
        }
        if ($substrac !== null){
            $formParams['subtract_totalreceipts'] = $this->apiClient->getSerializer()->toFormValue($substrac);
        }
       
 
        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } else if (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
 
        // make the API Call
        try
        {
            list($response, $httpHeader) = $this->apiClient->callApi(
                $resourcePath, $method,
                $queryParams, $httpBody,
                $headerParams
            );
 
            return array($response, $httpHeader);
        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
 
            throw $e;
        }
 
    }`
namun saat dijalankan mendapat error
`Caught exception: [404] Error connecting to the API (https://api.liqu.id/v1/manage/resellers/11111/add_reseller_debit_note) `

kode itu saya tambahkan di BillingApi.php

bisa bantu dicek kenapa?
thanks

**Comment by almazary** [comment]
@juniorriau 

Baik kami akan segera melakukan generate client libarary ulang, sepertinya memang belum ada...

Untuk melihat list url api yang dapat digunkan, bisa menuju ke https://api.liqu.id/docs

Terimakasih

**Comment by juniorriau** [comment]
@almazary
Oke siap

**Comment by juniorriau** [comment]
halo,
sudah ada perkembangan?

**Comment by liquidregistrar** [comment]
@juniorriau 

Silahkan menggunakan path "/resellers/{reseller_id}/transactions/debit_note"

Untuk melihat list url api yang dapat digunkan, bisa menuju ke https://api.liqu.id/docs

Terimakasih

**Comment by juniorriau** [comment]
Halo

ok thanks @liquidregistrar
