### ISSUE TITLE
Fetching All reseller without paging

### ISSUE THREAD

**Issue by juniorriau** [liquidregistrar/liquid-php#2]
Hi

di halaman ini https://api.liqu.id/docs#!/resellers/list_resellers
tidak ada opsi untuk mengambil semua reseller, sementara kita tidak tahu ada berapa total reseller.
jadi jika script menampilkan paging, batas limit paging tidak diketahui, misal kasus di reseller cuma ada 25, berarti ada 3 paging, sementara dari script dibuat static sampai 5, ketika jumlah reseller sudah mencapai 70, maka perlu edit manual script paging. opsi lain bisa mengambil page per page sampai hasil return API = 0 baru hasil setiap page di mmerger untuk dipaging ulang (saat ini kami memakai metode ini dan sedkit menyulitkan)
mungkin dibuatkan opsi mengambil semua reseller secara keseluruhan tanpa paging, jadi urusan pagging bisa dari script phpnya supaya tidak rancu

**Comment by juniorriau** [comment]
problem lain variable status tidak ada di hasil return api, sedangkan di list variable di https://api.liqu.id/docs#!/resellers/list_resellers ada kolom status reseller

**Comment by liquidregistrar** [comment]
Hai @juniorriau 

Jika ingin mendapatkan berapa jumlah record data yang tersedia dan paginationnya bisa dilihat di respon header api, seperti berikut:

![screenshot-api domainsas com 2017-10-23 10-42-21-019](https://user-images.githubusercontent.com/12673013/31871528-35ddd078-b7df-11e7-8241-8e715393f682.png)

"Link": => ini paginationnya
"X-Total-Count": "6" => ini adalah jumlah data


Cara mendapatkan header silakan lihat contoh berikut: https://github.com/liquidregistrar/liquid-php/blob/master/example.php#L66

problem lain variable status tidak ada di hasil return api, sedangkan di list variable di https://api.liqu.id/docs#!/resellers/list_resellers ada kolom status reseller => Ini maksutnya di return api apa ya? mohon berikan url apinya.

Terimakasih

**Comment by juniorriau** [comment]
x-total-count itu = total page?
untuk variable status ini maksudnya
![image](https://user-images.githubusercontent.com/3606652/31873006-93a0a4a0-b7ea-11e7-82c3-85f6d8ec70b0.png)
lihat gambar diatas, tidak ada variable status account (active/pending active/suspend). data pada gambar itu data reseller yang dalam status pending activation

**Comment by liquidregistrar** [comment]
"X-Total-Count" => jumlah record

lihat gambar diatas, tidak ada variable status account (active/pending active/suspend) => ini aksinya apa ya? create reseller? retrieve reseller?

**Comment by juniorriau** [comment]
untuk status itu aksi retrieve reseller.

jumlah record dalam 1 page yang di request apa keseluruhan downline? penjelasannya kurang mengena kesaya. karena di url api itu merequest x row data untuk page y. tidak ada opsi ambil data tanpa paging
![image](https://user-images.githubusercontent.com/3606652/31881433-b0b0b2d8-b80d-11e7-9c28-4922d2d6c391.png)

**Comment by liquidregistrar** [comment]
Jumlah seluruh record bpk, bukan jumlah perhalaman.
Kami tidak bisa menyediakan api tanpa pagination, karena akan memberatkan server kami.

Api retrieve reseller kami sudah mereturnkan index status bpk
![screenshot-api domainsas com 2017-10-23 17-25-26-530](https://user-images.githubusercontent.com/12673013/31884488-5cd37f2e-b817-11e7-9638-5898ca03f3d3.png)

Mohon periksa kembali skrip yg bpk buat

Terimakasih

**Comment by juniorriau** [comment]
output : 
![image](https://user-images.githubusercontent.com/3606652/31886640-674ecd2a-b81f-11e7-9582-350ca6513726.png)

tidak ada array key untuk status di output itu
kode memakai dari sample di file ini
https://github.com/liquidregistrar/liquid-php/blob/master/example.php 
ini kode yang kami jalankan
![image](https://user-images.githubusercontent.com/3606652/31886705-a9c56d8a-b81f-11e7-82e3-97017f869c49.png)

**Comment by juniorriau** [comment]
ini output test dari halaman https://api.liqu.id/docs#!/resellers/list_resellers memakai parent reseller id saya juga outputnya tidak ada data status reseller, apa mungkin karena perbedaan host API? dimana pada screenshot mas itu memakai api.domainsas.com sedangkan saya api.liqu.id
![image](https://user-images.githubusercontent.com/3606652/31886857-42694dfe-b820-11e7-86fd-d0da09162989.png)

**Comment by liquidregistrar** [comment]
Kami sudah melakukan cek lebih dalam, ternyata benar ada kondisi yang menyebabkan status tidak keluar, namun kami sudah perbaiki, silakan dicoba kembali.

Terimakasih

**Comment by juniorriau** [comment]
oke thanks

**Comment by juniorriau** [comment]
Hallo tanya lagi

`var_dump(json_decode(json_encode($httpHeader)),true);`

hasilnya bukan dalam array format ya?
![image](https://user-images.githubusercontent.com/3606652/32401553-54ad845e-c143-11e7-98c8-f782082124ef.png)
seperti text biasa saja
